INSERT INTO unidades.unidade(unid_nome, unid_sigla)
VALUES
    ('UNIDADE DE TECNOLOGIA DA INFORMACAO','UTI'),
    ('UNIDADE DE PESQUISA ESPACIAL','UPE'),
    ('UNIDADE DE TELECOMUNICACOES','UTC'),
    ('UNIDADE DE RELACIONAMENTO PUBLICO','URP');